Repository ADRE9/bunk-manager-mern, pull requests merged in 2021-03, with the labels that each got.

#28 Changed the styling of Server and client - Feature added as Gssoc'21 participant
  client/package-lock.json
  client/package.json
  package.json
Labels: GSSoC21, Level1, enhancement, good first issue

#32 Added styles to the headings in the Subject page
  client/package-lock.json
  client/src/components/pages/HomePage.js
  client/src/components/pages/SubjectPage.js
Labels: GSSoC21, Level1, enhancement, good first issue

#33 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: GSSoC21, Level1, enhancement, good first issue

#39 Logo Overlapping Issue Solved
  client/src/components/pagesComponents/AuthHeader.js
Labels: GSSoC21, Level0, good first issue

#41 Added labels to bottom nav icons
  client/src/components/pagesComponents/MobileNavigation.js
Labels: GSSoC21, Level1

#50 add contributing.md
  contributing.md
Labels: GSSoC21, Level1, documentation

#53 Added various security features
  index.js
  package.json
Labels: GSSoC21, Level2

#64 Adding the sender email and a suitable subject, issue #49
  utils/email.js
Labels: GSSoC21, Level1

#68 Added validation for semester in signup form
  client/src/components/pages/SignUpPage.js
Labels: GSSoC21, Level1, bug

#72 Fixed Issue #7 : Dark theme Implementation
  client/package-lock.json
  client/src/Themes/Theme.js
  client/src/assets/svg/book_lover_dark.svg
  client/src/components/App.js
  client/src/components/UI/AuthenticationCard.js
  client/src/components/pages/LoginPage.js
  client/src/components/pagesComponents/AuthHeader.js
  client/src/index.js
  client/src/providers/DarkThemeProvider.jsx
  package-lock.json
Labels: GSSoC21, Level3, enhancement

#79 Updated Readme.md Mern Stack
  README.md
Labels: GSSoC21, Level0, documentation

#75 Fixes Issue #70 : Dockerized the Project
  .dockerignore
  Dockerfile
  README.md
  client/.dockerignore
  client/Dockerfile
  client/package.json
  docker-compose.yml
  package.json
Labels: GSSoC21, Level3, bug, documentation, enhancement
