Repository ADRE9/bunk-manager-mern, pull requests merged in 2021-05, with the labels that each got.

#143 Readme modified
  README.md
Labels: GSSOC21, Level0

#153 Notfound page
  client/package-lock.json
  client/src/assets/svg/404.png
  client/src/components/App.js
  client/src/components/NotFound/NotFound.css
  client/src/components/NotFound/NotFound.js
  package-lock.json
Labels: GSSOC21, Level1

#159 Landing page for light theme based on new designs
  client/public/index.html
  client/src/Themes/Theme.js
  client/src/assets/svg/logoTickLight.png
  client/src/components/App.js
  client/src/components/pages/Home.js
  client/src/components/pagesComponents/bottom.js
  client/src/components/pagesComponents/navbar.js
  client/src/providers/DarkThemeProvider.jsx
Labels: GSSOC21, Level3
