Repository ADRE9/bunk-manager-mern, pull requests merged in 2021-04, with the labels that each got.

#73 Fixed Issue: 69 | Get In Touch Section Has added to the Footer!!!
  client/src/components/pagesComponents/Footer.js
Labels: GSSOC21, Level2, enhancement

#106 Add Card Menu
  client/src/components/UI/Cards/SubjectCard.js
Labels: GSSOC21, Level1, enhancement

#110 Made footer mobile responsive and increased icon sizes
  client/src/components/pagesComponents/Footer.js
Labels: GSSOC21, Level2, enhancement

#108 Changed the button name from SignUp to Register
  client/src/components/UI/LoginComponents/SignUpCard.js
Labels: GSSOC21, Level0

#121 Today Page prototype
  README.md
Labels: GSSOC21, Improvised UI, Level2

#122 google-login-signup
  client/package-lock.json
  client/package.json
  client/src/components/UI/Cards/SubjectCard.js
  client/src/components/UI/LoginComponents/LoginCard.js
  client/src/components/UI/LoginComponents/SignUpCard.js
  client/src/components/pages/HomePage.js
  client/src/components/pages/SignUpPage.js
  client/src/components/pages/SubjectPage.js
  client/src/components/pagesComponents/AuthHeader.js
  client/src/components/pagesComponents/Footer.js
  client/src/utils/cardUtil.js
  client/src/utils/cardUtilSub.js
  controller/user.js
  db/mongoose.js
  package-lock.json
  package.json
  routers/user.js
Labels: GSSOC21, Level3

#124 Added Edit Dialog And Timetable
  client/src/actions/actionTypes.js
  client/src/actions/timetableActions.js
  client/src/components/App.js
  client/src/components/UI/Cards/CardMenu.js
  client/src/components/pages/AddSubjectPage.js
  client/src/components/pages/EditSubjectPage.js
  client/src/components/pages/SignUpPage.js
  client/src/components/pages/TimetablePage.js
  client/src/components/pagesComponents/AuthHeader.js
  client/src/components/pagesComponents/UpdateForm.js
  client/src/reducers/index.js
  client/src/reducers/timetableReducer.js
  client/src/utils/cardUtilSub.js
Labels: GSSOC21, Level2

#129 Updated Readme- Added UI design file
  README.md
Labels: GSSOC21, Improvised UI, Level3

#130 Design - Login Page - Web and Mobile
  README.md
Labels: GSSOC21, Improvised UI, Level3

#133 Updated README - Sign up Page Design
  README.md
Labels: GSSOC21, Improvised UI, Level3

#138 Added Today Page Prototype
  README.md
Labels: GSSOC21, Level3

#136 Share Anything Page Prototype Added
  README.md
Labels: GSSOC21, Improvised UI, Level3
